/**
 * Inlined from lib/api-zod — Zod validators for all API routes.
 * Generated by orval v8.22.0 from openapi.yaml
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all patients with current vitals and risk
 */
export const ListPatientsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  bedNumber: zod.string(),
  age: zod.number(),
  ward: zod.string(),
  diagnosis: zod.string(),
  risk: zod.enum(["green", "amber", "red"]),
  latestVitals: zod.object({
    id: zod.number(),
    patientId: zod.number(),
    recordedAt: zod.string(),
    heartRate: zod.number(),
    spo2: zod.number(),
    bpSystolic: zod.number(),
    bpDiastolic: zod.number(),
    temperature: zod.number(),
    respiratoryRate: zod.number(),
  }),
  riskReason: zod.string().nullish(),
});
export const ListPatientsResponse = zod.array(ListPatientsResponseItem);

/**
 * @summary Create a new patient (with initial vitals) — used by the Nurse "Add Patient" form
 */
export const CreatePatientBody = zod.object({
  name: zod.string().min(1, "Name is required"),
  bedNumber: zod.string().min(1, "Bed number is required"),
  age: zod.coerce.number().int().positive("Age must be a positive number"),
  ward: zod.string().min(1, "Ward is required"),
  diagnosis: zod.string().min(1, "Diagnosis is required"),
  heartRate: zod.coerce.number(),
  spo2: zod.coerce.number(),
  bpSystolic: zod.coerce.number(),
  bpDiastolic: zod.coerce.number(),
  temperature: zod.coerce.number(),
  respiratoryRate: zod.coerce.number(),
});

export const CreatePatientResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  bedNumber: zod.string(),
  age: zod.number(),
  ward: zod.string(),
  diagnosis: zod.string(),
  risk: zod.enum(["green", "amber", "red"]),
  latestVitals: zod.object({
    id: zod.number(),
    patientId: zod.number(),
    recordedAt: zod.string(),
    heartRate: zod.number(),
    spo2: zod.number(),
    bpSystolic: zod.number(),
    bpDiastolic: zod.number(),
    temperature: zod.number(),
    respiratoryRate: zod.number(),
  }),
  riskReason: zod.string().nullish(),
});

/**
 * @summary Get a single patient with current vitals and risk
 */
export const GetPatientParams = zod.object({
  id: zod.coerce.number(),
});

export const GetPatientResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  bedNumber: zod.string(),
  age: zod.number(),
  ward: zod.string(),
  diagnosis: zod.string(),
  risk: zod.enum(["green", "amber", "red"]),
  latestVitals: zod.object({
    id: zod.number(),
    patientId: zod.number(),
    recordedAt: zod.string(),
    heartRate: zod.number(),
    spo2: zod.number(),
    bpSystolic: zod.number(),
    bpDiastolic: zod.number(),
    temperature: zod.number(),
    respiratoryRate: zod.number(),
  }),
  riskReason: zod.string().nullish(),
  vitalsHistory: zod.array(
    zod.object({
      id: zod.number(),
      patientId: zod.number(),
      recordedAt: zod.string(),
      heartRate: zod.number(),
      spo2: zod.number(),
      bpSystolic: zod.number(),
      bpDiastolic: zod.number(),
      temperature: zod.number(),
      respiratoryRate: zod.number(),
    }),
  ),
});

/**
 * @summary Get vitals history for a patient
 */
export const GetPatientVitalsParams = zod.object({
  id: zod.coerce.number(),
});

export const GetPatientVitalsResponseItem = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  recordedAt: zod.string(),
  heartRate: zod.number(),
  spo2: zod.number(),
  bpSystolic: zod.number(),
  bpDiastolic: zod.number(),
  temperature: zod.number(),
  respiratoryRate: zod.number(),
});
export const GetPatientVitalsResponse = zod.array(GetPatientVitalsResponseItem);

/**
 * @summary Add a vitals reading for a patient
 */
export const AddVitalsParams = zod.object({
  id: zod.coerce.number(),
});

export const AddVitalsBody = zod.object({
  heartRate: zod.number(),
  spo2: zod.number(),
  bpSystolic: zod.number(),
  bpDiastolic: zod.number(),
  temperature: zod.number(),
  respiratoryRate: zod.number(),
});

export const AddVitalsResponse = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  recordedAt: zod.string(),
  heartRate: zod.number(),
  spo2: zod.number(),
  bpSystolic: zod.number(),
  bpDiastolic: zod.number(),
  temperature: zod.number(),
  respiratoryRate: zod.number(),
});

/**
 * @summary Get notes for a patient
 */
export const GetPatientNotesParams = zod.object({
  id: zod.coerce.number(),
});

export const GetPatientNotesResponseItem = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  createdAt: zod.string(),
  role: zod.string(),
  rawText: zod.string(),
  isSoap: zod.boolean(),
  soapSubjective: zod.string().nullish(),
  soapObjective: zod.string().nullish(),
  soapAssessment: zod.string().nullish(),
  soapPlan: zod.string().nullish(),
});
export const GetPatientNotesResponse = zod.array(GetPatientNotesResponseItem);

/**
 * @summary Create a clinical note for a patient
 */
export const CreatePatientNoteParams = zod.object({
  id: zod.coerce.number(),
});

export const CreatePatientNoteBody = zod.object({
  role: zod.string(),
  rawText: zod.string(),
  isSoap: zod.boolean(),
  soapSubjective: zod.string().nullish(),
  soapObjective: zod.string().nullish(),
  soapAssessment: zod.string().nullish(),
  soapPlan: zod.string().nullish(),
});

export const CreatePatientNoteResponse = zod.object({
  id: zod.number(),
  patientId: zod.number(),
  createdAt: zod.string(),
  role: zod.string(),
  rawText: zod.string(),
  isSoap: zod.boolean(),
  soapSubjective: zod.string().nullish(),
  soapObjective: zod.string().nullish(),
  soapAssessment: zod.string().nullish(),
  soapPlan: zod.string().nullish(),
});

/**
 * @summary Get all Amber and Red risk patients hospital-wide
 */
export const GetAlertsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  bedNumber: zod.string(),
  age: zod.number(),
  ward: zod.string(),
  diagnosis: zod.string(),
  risk: zod.enum(["green", "amber", "red"]),
  latestVitals: zod.object({
    id: zod.number(),
    patientId: zod.number(),
    recordedAt: zod.string(),
    heartRate: zod.number(),
    spo2: zod.number(),
    bpSystolic: zod.number(),
    bpDiastolic: zod.number(),
    temperature: zod.number(),
    respiratoryRate: zod.number(),
  }),
  riskReason: zod.string().nullish(),
});
export const GetAlertsResponse = zod.array(GetAlertsResponseItem);

/**
 * @summary LLM explanation of why a patient is flagged
 */
export const ExplainRiskBody = zod.object({
  patientId: zod.number(),
  vitalsHistory: zod.array(
    zod.object({
      id: zod.number(),
      patientId: zod.number(),
      recordedAt: zod.string(),
      heartRate: zod.number(),
      spo2: zod.number(),
      bpSystolic: zod.number(),
      bpDiastolic: zod.number(),
      temperature: zod.number(),
      respiratoryRate: zod.number(),
    }),
  ),
  patientName: zod.string().nullish(),
  diagnosis: zod.string().nullish(),
});

export const ExplainRiskResponse = zod.object({
  explanation: zod.string(),
});

/**
 * @summary Convert raw voice/text transcript to a structured SOAP note
 */
export const CreateSoapNoteBody = zod.object({
  transcript: zod.string(),
  patientName: zod.string().nullish(),
  diagnosis: zod.string().nullish(),
});

export const CreateSoapNoteResponse = zod.object({
  subjective: zod.string(),
  objective: zod.string(),
  assessment: zod.string(),
  plan: zod.string(),
});

/**
 * @summary Translate text to Tamil
 */
export const TranslateTextBody = zod.object({
  text: zod.string(),
});

export const TranslateTextResponse = zod.object({
  translated: zod.string(),
});

/**
 * @summary Delete a clinical note (e.g. a Doctor's SOAP note) for a patient
 */
export const DeletePatientNoteParams = zod.object({
  id: zod.coerce.number(),
  noteId: zod.coerce.number(),
});

export const DeletePatientNoteResponse = zod.object({
  success: zod.boolean(),
  id: zod.number(),
});

/**
 * @summary Advance the shift simulation by one step — updates vitals for all patients
 */
export const SimulateShiftResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  bedNumber: zod.string(),
  age: zod.number(),
  ward: zod.string(),
  diagnosis: zod.string(),
  risk: zod.enum(["green", "amber", "red"]),
  latestVitals: zod.object({
    id: zod.number(),
    patientId: zod.number(),
    recordedAt: zod.string(),
    heartRate: zod.number(),
    spo2: zod.number(),
    bpSystolic: zod.number(),
    bpDiastolic: zod.number(),
    temperature: zod.number(),
    respiratoryRate: zod.number(),
  }),
  riskReason: zod.string().nullish(),
});
export const SimulateShiftResponse = zod.array(SimulateShiftResponseItem);
